---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: personopplysninger
  namespace: {{namespace}}
  labels:
    team: pdlfullmakt
spec:
  image: {{image}}:{{version}}
  team: pdlfullmakt
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /person/pdl-fullmakt-ui/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/pdl-fullmakt-ui/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      memory: 512Mi
