name: Build and Deploy pdl-fullmakt-ui

on:
  push:
    branches:
      - 'master'
      - 'dev/*'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pdl-fullmakt-ui2:${{ github.sha }}

jobs:
  build-app:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev')
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set node environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Build applications
        run: |
          npm ci
          npm run build

      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy-dev:
    name: Deploy to dev-gcp
    needs: build-app
    # if: startsWith(github.ref, 'refs/heads/dev')
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VARS: nais/dev/vars.yaml
          PRINT_PAYLOAD: true
#  deploy-prod:
#    name: Deploy to prod-gcp
#    needs: build-app
#    if: github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: nais/nais.yaml
#          VARS: nais/prod/vars.yaml
#          PRINT_PAYLOAD: true
